baseURL = "/mongo-java-driver/4.1"
languageCode = "en-us"
title = "MongoDB JVM Drivers"
theme = "mongodb"
canonifyURLs = false
disableHugoGeneratorInject = true
disableKinds = ["section", "taxonomy", "taxonomyTerm", "404"]

[blackfriday]
  plainIdAnchors = true

[[menu.main]]
    name = "Source Code"
    pre = "<i class='fa fa-github'></i>"
    weight = 90
    identifier = "githubLink"
    url = "https://github.com/mongodb/mongo-java-driver/tree/master"
