baseurl = "/mongo-java-driver/3.4"
languageCode = "en-us"
title = "MongoDB Java Driver"
theme = "mongodb"
canonifyurls = false

[blackfriday]
  plainIdAnchors = true


# Update versions in mongodb.toml as well
[[menu.main]]
    name = "API Documentation"
    pre = "<i class='fa fa-file-text-o'></i>"
    weight = 90
    identifier = "apiDocs"
    url = "http://api.mongodb.com/java/3.4"

[[menu.main]]
    name = "Source Code"
    pre = "<i class='fa fa-github'></i>"
    weight = 90
    identifier = "githubLink"
    url = "https://github.com/mongodb/mongo-java-driver/tree/master"
